stages:
    - build

server:
    stage: build
    image: eclipse-temurin:17
    script:
        ./server/gradlew build
    artifacts:
        name: "Server"
        paths:
            - "**/target/*.jar"

client:
    stage: build
    image: eclipse-temurin:17
    script:
        ./client/gradlew build
    artifacts:
        name: "Client"
        paths:
             - "**/target/*.jar"
