spring:
  security:
    oauth2:
      client:
        registration:
          czcv2:
            client-id: czcv2
            client-secret: secret
            client-authentication-method: client_secret_basic
            client-name: czcv2
            redirect-uri: http://127.0.0.1:9080/login/oauth2/code/czcv2
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
            provider: czcv2_auth
        provider:
          czcv2_auth:
            issuer-uri: http://10.0.2.15:9000